%YAML 1.1
---
###################################################################
###################################################################
####                 _______   _                    _____      ####
####         /\     |__   __| | |          /\      / ____|     ####
####        /  \       | |    | |         /  \    | (___       ####
####       / /\ \      | |    | |        / /\ \    \___ \      ####
####      / ____ \     | |    | |____   / ____ \   ____) |     ####
####     /_/    \_\    |_|    |______| /_/    \_\ |_____/      ####
####                                                           ####
###################################################################
#  For more details about the config values see:
#  https://pnnl-atlas.readthedocs.io
###################################################################

########################
# Execution parameters
########################
# max cores per process
threads: 12
# Memory for most jobs especially from BBtools, which are memory demanding
java_mem: 90
# can be a subset of threads or altered if rule run_spades or run_megahit are being defined differently in your cluster configuration
assembly_threads: 8
# in GB
assembly_memory: 250
# Local directory for temp files, useful for cluster execution without shared file system
tmpdir: /tmp
database_dir: /home/kiesers/scratch/Atlas/databases

########################
# Quality control
########################
# remove (PCR)-duplicated reads using clumpify
deduplicate: true
duplicates_only_optical: false
duplicates_allow_substitutions: 2
# used to trim adapters from reads and read ends
preprocess_adapters: /home/kiesers/scratch/Atlas/databases/adapters.fa
preprocess_minimum_base_quality: 10
preprocess_minimum_passing_read_length: 51
# 0.05 requires at least 5 percent of each nucleotide per sequence
preprocess_minimum_base_frequency: 0.05
preprocess_adapter_min_k: 8
preprocess_allowable_kmer_mismatches: 1
preprocess_reference_kmer_match_length: 27
# error correction where PE reads overlap
error_correction_overlapping_pairs: true
#contamination references can be added such that -- key: /path/to/fasta
contaminant_references:
  rRNA: /home/kiesers/scratch/Atlas/databases/silva_rfam_all_rRNAs.fa
  PhiX: /home/kiesers/scratch/Atlas/databases/phiX174_virus.fa
  mouse: /home/kiesers/scratch/Atlas/databases/host_genome/Mus_musculus.GRCm38.dna.toplevel.fa.gz
# We won't allow large indels
contaminant_max_indel: 20
contaminant_min_ratio: 0.65
contaminant_kmer_length: 13
contaminant_minimum_hits: 1
contaminant_ambiguous: best


########################
# Pre-assembly-processing
########################

normalize_reads_before_assembly: false
# target kmer depth
normalization_target_depth: 10000
normalization_kmer_length: 21
normalization_minimum_kmers: 3

error_correction_before_assembly: true

# join R1 and R2 at overlap; unjoined reads are still utilized
merge_pairs_before_assembly: true
# extend reads while merging to this many nucleotides
merging_extend2: 40
# Iterations are performed until extend2 x iterations
merging_flags: ecct iterations=5
merging_k: 62


########################
# Assembly
########################
# megahit OR spades
assembler: spades

# Megahit
#-----------
# 2 is for metagenomes, 3 for genomes with 30x coverage
megahit_min_count: 2
megahit_k_min: 21
megahit_k_max: 121
megahit_k_step: 20
megahit_merge_level: 20,0.98
megahit_prune_level: 2
megahit_low_local_ratio: 0.2
# ['default','meta-large','meta-sensitive']
megahit_preset: default

# Spades
#------------
spades_skip_BayesHammer: true
spades_k: '21,33,55,77,99,127'

spades_use_scaffolds: true
# Filtering
#------------
prefilter_minimum_contig_length: 200
# filter out assembled noise
# this is more important for assemblys from megahit
filter_contigs: true
# trim contig tips
contig_trim_bp: 0
# require contigs to have read support
minimum_average_coverage: 0.8
minimum_percent_covered_bases: 80
minimum_mapped_reads: 0
# after filtering
minimum_contig_length: 300

########################
# Gene catalog
#######################
genecatalog:
  clustermethod: linclust # cd-hit-est or cluster or linclust see mmseqs for more details
  minlength_nt: 100
  minid: 0.9
  coverage: 0.9
  extra: ""

########################
# Quantification
########################

# Mapping reads to contigs
#--------------------------
contig_min_id: 0.9
contig_map_paired_only: true
contig_max_distance_between_pairs: 1000
maximum_counted_map_sites: 10

# Feature count
#-----------------
contig_count_multi_mapped_reads: false
# bp overlap of sequence to predicted gene
minimum_region_overlap: 1
feature_counts_allow_overlap: true


########################
# Binning
########################
perform_genome_binning: true
maxbin_max_iteration: 50
maxbin_min_contig_length: 200
maxbin_prob_threshold: 0.9

# new
final_binner: DASTool
binner:
  - metabat
  - maxbin
binning_min_contig_length: 1500 # metabat needs >1500
metabat:
  sensitivity: sensitive

concoct:
  Nexpected_clusters: 200
  read_length: 250
  Niterations: 500

maxbin:
  max_iteration: 50
  prob_threshold: 0.9


genome_dereplication:
  ANI: 0.99
  overlap: 0.6
  opt_parameters: ""
  filter:
      noFilter: false
      length: 5000
      completeness: 50
      contamination: 10
  score:
      completeness: 1
      contamination: 5
      N50: 0.5
      length: 0.1
########################
# Gene catalog
#######################
genecatalog:
  source: genomes  # which predicted proteins should be used for the gene catalog
  clustermethod: linclust # cd-hit-est or cluster or linclust see mmseqs for more details
  minlength_nt: 100
  minid: 0.5
  coverage: 0.8
  extra: ""
  SubsetSize: 500000






########################
# Annotation
########################
translation_table: 11
diamond_db: /home/kiesers/scratch/Atlas/databases/refseq.dmnd
diamond_run_mode: fast
diamond_top_seqs: 2
diamond_e_value: 1.0e-06
diamond_min_identity: 50
diamond_query_coverage: 60
diamond_gap_open: 11
diamond_gap_extend: 1
diamond_block_size: 2
diamond_index_chunks: 4

# LCA taxonomic annotation
#--------------------------
refseq_namemap: /home/kiesers/scratch/Atlas/databases/refseq.db
refseq_tree: /home/kiesers/scratch/Atlas/databases/refseq.tree
summary_method: lca
aggregation_method: lca-majority
majority_threshold: 0.51


########################
# SAMPLES
########################
samples:
